---
--- Autogenerated file, modify it to suit your needs
--- Date: 2026-03-15
--- License: *MIT
---
local pegasus = require("pegasus")
local lunajson = require("lunajson")
local env = require("env")

local server = pegasus:new({
    port = env.port
})

server:start(function (request, response)
    response:addHeader("Content-Type", "application/json")
    response:write(lunajson.encode({ message = "Your luapi application is ready!" }))
    return response:close()
end)
